# Auto-generated by scripts/export_artifacts.py — do not edit by hand.
# Re-run that script after retraining the model to update these constants.
HF_REPO_ID = "marknovak/TaxonBodyMassML"

CHECKSUMS = {
    # XGBoost (original method)
    "model.ubj": "0fdb5d375e6158cd8eed635330f9f06d1d3054af65ee3857ff6890d2e15e94ed",  # noqa: E501
    "calibration.json": "814fd4dde6421e0509de77d778dfb62f5beab9d129af1744b5f1aa59095bc1bd",  # noqa: E501
    "calibration_by_rank.json": "dd409f4d0f7e544d36309328c89135d8669539e365bd93076b639e5f8be01280",  # noqa: E501
    "categories.json": "910394f7a8fa2d4d34b3a559ad170f7d6d4909f9ad88167d3820e6701ca0b377",  # noqa: E501
    "lookup.json": "ba530ab9b34eb5a0c236fd6c1ebba0e6fa04ec3287011887681146282dd6cd46",  # noqa: E501
    # Entity Embeddings
    "embeddings.json": "cce9b15b709e72a7caf6b1c0d771ea3e0b629085a88de6bf2bc761e5cc9b74c0",  # noqa: E501
    "model_ee.ubj": "3bff6e3218f949744f4d1bcbe2cee5cf2bbe60b3886543d7e0c85629502683cc",  # noqa: E501
    "calibration_ee.json": "cba32526436d1eb3f8f2965bf4f6e12ad105e9baf4d038a44fc5a03937dde1b2",  # noqa: E501
    "calibration_by_rank_ee.json": "8a1579dd5f3fbf1ab063819f6d8304c60a30064f5bbeb938d2b3ae3217e34fd6",  # noqa: E501
}
