# Auto-generated by scripts/export_artifacts.py — do not edit by hand.
# Re-run that script after retraining the model to update these constants.
HF_REPO_ID = "marknovak/TaxonBodyMassML"

CHECKSUMS = {
    "model.ubj": "6f94483f99af5f3792cd602b70735b5f34f3b7329b6cd76bf88ac33775fa4ac8",  # noqa: E501
    "calibration.json": "931b981419b8950e85be8195b5837855f89716c6f9353c4062ea7fce4a72c6ca",  # noqa: E501
    "categories.json": "c1db62061c22673bde63b3347246373c4340e3a92d35804df892b1ec9938298d",  # noqa: E501
}
