# Auto-generated by scripts/export_artifacts.py — do not edit by hand.
# Re-run that script after retraining the model to update these constants.
HF_REPO_ID = "marknovak/TaxonBodyMassML"

CHECKSUMS = {
    "model.ubj": "4a5baab4f80a8d3bc724e7292d23b5b50ee5d6980012c660a680c46765014991",
    "calibration.json": "71e0f26d6dd93afa4cb7944bb9eaa2be372b0fad9fae10671ac3e24eddae8e9a",
    "categories.json": "7f83d942598093d5f759bf2125ca333b52b1f00bf226ab711038f3856bc311dc",
}
