version: "3.9"

services:
  regressor:
    build: .
    container_name: regressor_api
    expose:
      - "8000"
    command: >
      gunicorn
      -w 1
      -b 0.0.0.0:8000
      'regressor:create_wsgi_app()'
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --url http://regressor:8000
    restart: unless-stopped
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - regressor